### ISSUE TITLE
React Hooks

### ISSUE THREAD

**Issue by ybwdaisy** [lasoplanet/technical-seminar#1]
1. React 推出 hooks 的动机？
2. useState，useCallback，useEffect，useRef，useContext，useMemo 原理解析？
3. 如何自定义 hooks ？
4. 优秀好用 hooks 推荐？

**Comment by dongyc1013** [comment]
1. 想让函数式组件想得到记忆功能，每次调用都可以获取到上次作用域的变量。由于函数式组件没有实例，想实现这个功能需要修改函数上的属性，但是这样组件一旦被一处以上使用就会导致混乱。所以需要在fiber(代表视图上的一个ReactElement)做记录，hook就是一些闭包函数，可以在函数组件重新渲染时获取到上次渲染作用域的变量，实现记忆功能。
2. 接上条，所有hooks都是闭包函数，从useCallback函数体内可以获取到上次渲染的值就可以验证这一点。以useCallback举例：每次函数渲染顺便执行hooks，遍历依赖列表做对比，如果不一致就会重新将hook对象的state属性赋值为hook函数的参数，否则使用利用闭包特性缓存的值。
3. 灵活利用官方提供的基础hooks。
4. react-query、recoil、SWR、formik。

**Comment by ybwdaisy** [comment]
useState 导出的 setState 为什么不支持回调？

**Comment by ybwdaisy** [comment]
@songxiaoliang React 推出 hooks 的动机？

**Comment by ybwdaisy** [comment]
优秀 hooks 推荐:
`import { useRef, useCallback } from 'react';

export function usePersistFn(fn) {
    const fnRef = useRef(fn);
    fnRef.current = fn;
    return useCallback((...args) => fnRef.current?.apply(void 0, args), []);
}
`

**Comment by ybwdaisy** [comment]
@dongyc1013 如何结合 AOP 使用？
