### ISSUE TITLE
Taro 插件功能

### ISSUE THREAD

**Issue by wiseqingyang** [lasoplanet/technical-seminar#2]
Taro 引入了插件化机制，目的是为了让开发者能够通过编写插件的方式来为 Taro 拓展更多功能或为自身业务定制个性化功能。
- 插件的使用方法；
- 如何编写一个插件；
- 分析现有插件的实现；
- 现有业务有哪些可以通过插件提升效率。

**Comment by dongyc1013** [comment]
使用插件式架构的主要优势有：
- 插件与核心代码相互独立，无需修改核心代码就可以扩展功能、改写现有功能、移除功能
- 插件遵循单一职责原则
- 易于定制化与社区贡献
在taro、webpack、rollup等编译工具中，插件的行为都差不多：
- 遵循官方统一规范
- 可在各阶段事件比如buildStart、emitAssets等挂载hooks，各阶段的hooks接收参数不同，可以通过改写参数，改写返回值等定制原有行为。

比如@tarojs/plugin-mini-ci就是在plugin中写入一些配置，监听build结束将配置传给miniprogram-ci来实现自动上传小程序。

**Comment by ybwdaisy** [comment]
@wiseqingyang 如何通过 Taro 插件来控制环境变量？
