### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by ybwdaisy** [lasoplanet/technical-seminar#4]
1. WebAssembly 是什么？
2. 运行 1 个 Demo？
3. 了解部分原理？

**Comment by ybwdaisy** [comment]
AssemblyScript 官网：https://www.assemblyscript.org/introduction.html

**Comment by xiaoxuan520** [comment]
写一个例子：图片加水印（去水印）

**Comment by ybwdaisy** [comment]
ffmpeg: https://github.com/ffmpegwasm/ffmpeg.wasm

**Comment by ybwdaisy** [comment]
WebAssembly文本格式: https://developer.mozilla.org/zh-CN/docs/WebAssembly/Understanding_the_text_format

> 写一个例子：图片加水印（去水印）

![EEB99CE2-8BB6-425A-A0B5-14D481375165](https://user-images.githubusercontent.com/6270043/143674663-a1c9f422-fe97-40f7-9727-80d83259af1f.png)
